apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-pv
  namespace: devops
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azure-disk
  csi:
    driver: disk.csi.azure.com
    volumeHandle: /subscriptions/<subscription-id>/resourceGroups/devops-rg/providers/Microsoft.Compute/disks/<disk-name>

