apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: azure-disk
